controllers/AuthController.php
<?php

namespace app\controllers;

use app\forms\LoginForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class AuthController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionLogin()
    {
        $this->layout = '//manage';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return Yii::$app->getResponse()->redirect(['/manage']);
        }

        $model->password = '';
        return $this->render('login', ['model' => $model]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return Yii::$app->getResponse()->redirect(['/manage']);
    }
}

views/layouts/_footer.php
<div id="rec47015295" class="r t-rec t-rec_pt_60 t-rec_pb_60"
     style="padding-top:60px;padding-bottom:60px;background-color:#000000; " data-record-type="564"
     data-bg-color="#000000">
    <div class="t564">
        <div class="t-container">
            <div class="t-col t-col_4 t-prefix_4 t-align_center"><img
                        src="https://static.tildacdn.com/tild6135-3532-4339-b939-333732353939/nsbook.png"
                        class="t564__img" imgfield="img">
                <?php $contact = \app\models\Contact::find()->one();?>
                <?php if ($contact): echo $contact->content; endif; ?>
                <div class="t-sociallinks">
                    <div class="t-sociallinks__wrapper">
                        <div class="t-sociallinks__item"><a href="https://vk.com/id482754392" target="_blank">
                                <svg class="t-sociallinks__svg" version="1.1" id="Layer_1"
                                     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                     x="0px" y="0px" width="30px" height="30px" viewBox="0 0 48 48"
                                     enable-background="new 0 0 48 48" xml:space="preserve"><desc>VK</desc>
                                    <path style="fill:#ffffff;"
                                          d="M47.761,24c0,13.121-10.639,23.76-23.76,23.76C10.878,47.76,0.239,37.121,0.239,24c0-13.123,10.639-23.76,23.762-23.76C37.122,0.24,47.761,10.877,47.761,24 M35.259,28.999c-2.621-2.433-2.271-2.041,0.89-6.25c1.923-2.562,2.696-4.126,2.45-4.796c-0.227-0.639-1.64-0.469-1.64-0.469l-4.71,0.029c0,0-0.351-0.048-0.609,0.106c-0.249,0.151-0.414,0.505-0.414,0.505s-0.742,1.982-1.734,3.669c-2.094,3.559-2.935,3.747-3.277,3.524c-0.796-0.516-0.597-2.068-0.597-3.171c0-3.449,0.522-4.887-1.02-5.259c-0.511-0.124-0.887-0.205-2.195-0.219c-1.678-0.016-3.101,0.007-3.904,0.398c-0.536,0.263-0.949,0.847-0.697,0.88c0.31,0.041,1.016,0.192,1.388,0.699c0.484,0.656,0.464,2.131,0.464,2.131s0.282,4.056-0.646,4.561c-0.632,0.347-1.503-0.36-3.37-3.588c-0.958-1.652-1.68-3.481-1.68-3.481s-0.14-0.344-0.392-0.527c-0.299-0.222-0.722-0.298-0.722-0.298l-4.469,0.018c0,0-0.674-0.003-0.919,0.289c-0.219,0.259-0.018,0.752-0.018,0.752s3.499,8.104,7.573,12.23c3.638,3.784,7.764,3.36,7.764,3.36h1.867c0,0,0.566,0.113,0.854-0.189c0.265-0.288,0.256-0.646,0.256-0.646s-0.034-2.512,1.129-2.883c1.15-0.36,2.624,2.429,4.188,3.497c1.182,0.812,2.079,0.633,2.079,0.633l4.181-0.056c0,0,2.186-0.136,1.149-1.858C38.281,32.451,37.763,31.321,35.259,28.999"/></svg>
                            </a></div>
                        <div class="t-sociallinks__item"><a
                                    href="https://www.youtube.com/channel/UCci7BEfrGFvSFAP7oOb-Jxw" target="_blank">
                                <svg class="t-sociallinks__svg" version="1.1" id="Layer_1"
                                     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                     x="0px" y="0px" width="30px" height="30px" viewBox="-455 257 48 48"
                                     enable-background="new -455 257 48 48" xml:space="preserve"><desc>Youtube
                                    </desc>
                                    <path style="fill:#ffffff;"
                                          d="M-431,257.013c13.248,0,23.987,10.74,23.987,23.987s-10.74,23.987-23.987,23.987s-23.987-10.74-23.987-23.987S-444.248,257.013-431,257.013z M-419.185,275.093c-0.25-1.337-1.363-2.335-2.642-2.458c-3.054-0.196-6.119-0.355-9.178-0.357c-3.059-0.002-6.113,0.154-9.167,0.347c-1.284,0.124-2.397,1.117-2.646,2.459c-0.284,1.933-0.426,3.885-0.426,5.836s0.142,3.903,0.426,5.836c0.249,1.342,1.362,2.454,2.646,2.577c3.055,0.193,6.107,0.39,9.167,0.39c3.058,0,6.126-0.172,9.178-0.37c1.279-0.124,2.392-1.269,2.642-2.606c0.286-1.93,0.429-3.879,0.429-5.828C-418.756,278.971-418.899,277.023-419.185,275.093zM-433.776,284.435v-7.115l6.627,3.558L-433.776,284.435z"/></svg>
                            </a></div>
                        <div class="t-sociallinks__item"><a href="https://www.instagram.com/ns_book/"
                                                            target="_blank">
                                <svg class="t-sociallinks__svg" version="1.1" id="Layer_1"
                                     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                                     width="30px" height="30px" viewBox="0 0 30 30" xml:space="preserve"><desc>
                                        Instagram
                                    </desc>
                                    <path style="fill:#ffffff;"
                                          d="M15,11.014 C12.801,11.014 11.015,12.797 11.015,15 C11.015,17.202 12.802,18.987 15,18.987 C17.199,18.987 18.987,17.202 18.987,15 C18.987,12.797 17.199,11.014 15,11.014 L15,11.014 Z M15,17.606 C13.556,17.606 12.393,16.439 12.393,15 C12.393,13.561 13.556,12.394 15,12.394 C16.429,12.394 17.607,13.561 17.607,15 C17.607,16.439 16.444,17.606 15,17.606 L15,17.606 Z"></path>
                                    <path style="fill:#ffffff;"
                                          d="M19.385,9.556 C18.872,9.556 18.465,9.964 18.465,10.477 C18.465,10.989 18.872,11.396 19.385,11.396 C19.898,11.396 20.306,10.989 20.306,10.477 C20.306,9.964 19.897,9.556 19.385,9.556 L19.385,9.556 Z"></path>
                                    <path style="fill:#ffffff;"
                                          d="M15.002,0.15 C6.798,0.15 0.149,6.797 0.149,15 C0.149,23.201 6.798,29.85 15.002,29.85 C23.201,29.85 29.852,23.202 29.852,15 C29.852,6.797 23.201,0.15 15.002,0.15 L15.002,0.15 Z M22.666,18.265 C22.666,20.688 20.687,22.666 18.25,22.666 L11.75,22.666 C9.312,22.666 7.333,20.687 7.333,18.28 L7.333,11.734 C7.333,9.312 9.311,7.334 11.75,7.334 L18.25,7.334 C20.688,7.334 22.666,9.312 22.666,11.734 L22.666,18.265 L22.666,18.265 Z"></path></svg>
                            </a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/layouts/_header.php
<div id="header" class="r t-rec">
    <div class="t396">
        <div class="t396__artboard">
            <div class="t396__elem tn-elem tn-elem__479724671521361634932 t-animate" data-elem-id="1521361634932">
                <a class="tn-atom" href="/site/index#rec47015278">Создать фотокнигу</a>
            </div>
            <div class="t396__elem tn-elem tn-elem__479724671521361964301" data-elem-id="1521361964301">
                <div class="tn-atom">
                    <img class="tn-atom__img t-img" src="<?= Yii::getAlias("@web"); ?>/logo-header.png">
                </div>
            </div>
            <div class="t396__elem tn-elem tn-elem__479724671521364655339" data-elem-id="1521364655339">
                <a class="tn-atom" href="/site/index#rec47015279">Галерея</a>
            </div>
            <div class="t396__elem tn-elem tn-elem__479724671521364767677" data-elem-id="1521364767677">
                <a class="tn-atom" href="/site/index#rec47425984">FAQ</a>
            </div>
            <div class="t396__elem tn-elem tn-elem__479724671521364799030" data-elem-id="1521364799030">
                <a class="tn-atom" href="/site/index#rec47015295">Контакты</a>
            </div>
        </div>
    </div>
</div>

views/layouts/main.php
<?php /* @var $this \yii\web\View */ ?>
<?php /* @var $content string */ ?>
<?php use yii\helpers\Html; ?>
<?php use app\assets\AppAsset; ?>
<?php AppAsset::register($this); ?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=1280"/>
    <script type="text/javascript">window.noAdaptive = true;</script>
    <meta property="og:title" content="<?= Html::encode($this->title); ?>"/>
    <meta property="og:description" content="<?= Html::encode($this->title); ?>"/>
    <meta property="og:type" content="website"/>
    <meta property="og:image" content="<?= Yii::getAlias("@web"); ?>/logo-header.png"/>
    <meta name="format-detection" content="telephone=no"/>
    <meta name="description" content="<?= Html::encode($this->title); ?>"/>
    <link rel="icon" type="image/png" href="<?= Yii::getAlias("@web"); ?>/logo-header.png"/>
    <?= Html::csrfMetaTags(); ?>
    <title><?= Html::encode($this->title); ?></title>
    <?php $this->head(); ?>
</head>
<body class="t-body" style="margin:0;">
<?= $this->render("_header"); ?>
<?php $this->beginBody(); ?>
<div id="allrecords" class="t-records" data-hook="blocks-collection-content-node" data-tilda-project-id="359550"
     data-tilda-page-id="2433940" data-tilda-page-alias="nsbook2" data-tilda-formskey="77cb59c4071f895e54182c3105a11260"
     data-blocks-animationoff="yes">
    <?= $content; ?>
    <?= $this->render("_footer"); ?>
</div>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/layouts/manage.php
<?php /** @var \yii\web\View $this */ ?>
<?php /** @var string $content */ ?>
<?php \app\assets\ManageAsset::register($this); ?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language; ?>">
<head>
    <meta charset="<?= Yii::$app->charset; ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= yii\helpers\Html::csrfMetaTags() ?>
    <title><?= yii\helpers\Html::encode($this->title); ?></title>
    <?php $this->head(); ?>
</head>
<body>
<?php $this->beginBody(); ?>

<div class="wrap <?php if (Yii::$app->user->isGuest): ?>wrap-login<?php endif; ?>">
    <?php if (!Yii::$app->user->isGuest): ?>
        <?php
        yii\bootstrap\NavBar::begin([
            "brandLabel" => "Управление",
            "brandUrl" => ["/manage"],
            "options" => [
                "class" => "navbar-inverse navbar-fixed-top",
            ],
        ]);
        echo yii\bootstrap\Nav::widget([
            "options" => ["class" => "navbar-nav navbar-right"],
            "activateParents" => true,
            "items" => [
                ["label" => "Логи", "url" => ["/manage/log/index"]],
                ["label" => "Обратная связь", "url" => ["/manage/feedback/index"]],


                [
                    "label" => "Настройки сайта",
                    "items" => [
                        ["label" => "FAQ", "url" => ["/manage/faq/index"]],
                        "<li class=\"divider\"></li>",
                        ["label" => "Галерея", "url" => ["/manage/gallery/index"]],
                        "<li class=\"divider\"></li>",
                        ["label" => "Отзывы", "url" => ["/manage/review/index"]],
                        "<li class=\"divider\"></li>",
                        ["label" => "Контакты", "url" => ["/manage/contact/index"]],
                        "<li class=\"divider\"></li>",
                        ["label" => "Видео", "url" => ["/manage/video/index"]],
                    ],
                ],
                [
                    "label" => "Клиенты и заказы",
                    "items" => [
                        ["label" => "Клиенты", "url" => ["/manage/client/index"]],
                        "<li class=\"divider\"></li>",
                        ["label" => "Заказы", "url" => ["/manage/order/index"]],
                    ],
                ],
                [
                    "label" => "Настройка формы",
                    "items" => [
                        ["label" => "Обложки", "url" => "/manage/cover/index"],
                        "<li class=\"divider\"></li>",
                        ["label" => "Посты и цены", "url" => "/manage/post-price/index"],
                    ],
                ],
                [
                    "label" => "Профиль",
                    "items" => [
                        ["label" => "Изменить пароль", "url" => "/manage/user/change-password"],
                        "<li class=\"divider\"></li>",
                        (
                            "<li>"
                            . yii\helpers\Html::beginForm(["/auth/logout"], "post")
                            . yii\helpers\Html::submitButton(
                                "Logout (" . Yii::$app->user->identity->email . ")",
                                ["class" => "btn btn-link logout"]
                            )
                            . yii\helpers\Html::endForm()
                            . "</li>"
                        )
                    ],
                ],

            ],
        ]);
        yii\bootstrap\NavBar::end();
        ?>
    <?php endif; ?>
    <div class="container">
        <?= yii\widgets\Breadcrumbs::widget([
            "links" => isset($this->params["breadcrumbs"]) ? $this->params["breadcrumbs"] : [],
            "homeLink" => [
                "label" => "Главная",
                "url" => ["/manage"]
            ]]); ?>
        <?= app\widgets\Alert::widget(); ?>
        <?= $content; ?>
    </div>
</div>
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>